app:
  camera_index: 0
  window_name: "Li-Vision"
  run_mode: "train"      # collect | train | inference

pipeline:
  model_path: "src/models/hand_landmarker.task"
  num_hands: 2

# ---------------------------------------------------
# CONFIGURAÇÃO DE DETECÇÃO
# ---------------------------------------------------
detection:
  mode: "dynamic_ml"             # rules | ml | dynamic_ml | hybrid

  # parâmetros globais do DetectorManager
  min_score: 0.7
  stability_frames: 3
  cooldown_frames: 10


# ---------------------------------------------------
# DETECTORES BASEADOS EM REGRAS
# ---------------------------------------------------
rules:
  enabled: true

  letters:
    - A
    - B
    - C
    - D
    - E


# ---------------------------------------------------
# ML ESTÁTICO (gestos sem movimento)
# ---------------------------------------------------
ml:
  enabled: true

  confidence_threshold: 0.75


# ---------------------------------------------------
# ML DINÂMICO (gestos com movimento)
# ---------------------------------------------------
dynamic_ml:
  enabled: true

  confidence_threshold: 0.75

  window_size: 15