import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppSpacing } from "@/constants/theme";

export const transcriptionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppColors.backgroundAlt },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: AppSpacing.xl,
    paddingTop: 12,
    paddingBottom: 12,
  },
  title: { color: AppColors.text.primary, fontSize: 22, fontWeight: "800" },
  inputArea: { paddingHorizontal: AppSpacing.xl },
  inputContainer: {
    backgroundColor: "#1a2230",
    borderRadius: AppRadius.xl,
    borderWidth: 1,
    borderColor: "#2a3548",
    overflow: "hidden",
  },
  input: {
    color: AppColors.text.primary,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: AppSpacing.sm,
    minHeight: 60,
    maxHeight: 100,
    textAlignVertical: "top",
  },
  inputFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  charCount: { color: "#697688", fontSize: 12 },
  translateBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: AppColors.primary,
    paddingHorizontal: AppSpacing.xl,
    paddingVertical: AppSpacing.sm,
    borderRadius: 10,
  },
  translateBtnDisabled: { backgroundColor: "#2a3548", opacity: 0.5 },
  translateBtnText: { color: "#081018", fontWeight: "700", fontSize: 14 },
  webviewContainer: {
    flex: 1,
    margin: AppSpacing.xl,
    marginTop: 12,
    borderRadius: AppRadius.xl,
    overflow: "hidden",
    backgroundColor: AppColors.backgroundAlt,
  },
  webview: { flex: 1, backgroundColor: AppColors.backgroundAlt },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    backgroundColor: AppColors.backgroundAlt,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: { color: "#8a92a3", fontSize: 14 },
  subtitleBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
    backgroundColor: "rgba(16, 20, 26, 0.85)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  subtitleText: { color: "#dfe2eb", fontSize: 13, flex: 1 },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: AppSpacing.sm,
    paddingHorizontal: AppSpacing.xl,
  },
  footerText: { color: "#697688", fontSize: 11 },
});
