import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppSpacing } from "@/constants/theme";

export const collectStaticStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.backgroundAlt,
    padding: AppSpacing.xl,
    paddingTop: 50,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    marginBottom: AppSpacing.xl,
  },
  title: { fontSize: 24, fontWeight: "bold", color: AppColors.text.primary },
  cameraContainer: {
    backgroundColor: AppColors.surface,
    borderRadius: 15,
    overflow: "hidden",
    position: "relative",
    marginBottom: AppSpacing.xl,
  },
  permissionBox: { flex: 1, alignItems: "center", justifyContent: "center" },
  landmarkDot: {
    position: "absolute",
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: AppColors.primary,
  },
  form: { gap: 15 },
  label: { color: AppColors.text.secondary, fontSize: 14, fontWeight: "bold" },
  input: {
    backgroundColor: AppColors.surface,
    color: AppColors.primary,
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AppColors.border.cyan,
    fontSize: 18,
    fontWeight: "bold",
  },
  buttonRow: { flexDirection: "column", gap: 10, marginTop: 10 },
  captureBtn: {
    backgroundColor: AppColors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 15,
    borderRadius: 10,
    gap: 10,
  },
  captureBtnText: { color: "#000", fontWeight: "bold", fontSize: 16 },
  finalizeBtn: {
    backgroundColor: AppColors.accent.green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 15,
    borderRadius: 10,
    gap: 10,
  },
  finalizeBtnText: { color: AppColors.text.primary, fontWeight: "bold", fontSize: 16 },
  stats: { color: AppColors.text.secondary, textAlign: "center", marginTop: 10 },
  chipScroll: { marginBottom: 10 },
  chip: {
    backgroundColor: "#262a31",
    paddingHorizontal: 15,
    paddingVertical: AppSpacing.sm,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "transparent",
  },
  chipActive: {
    borderColor: AppColors.primary,
    backgroundColor: "rgba(0, 229, 255, 0.15)",
  },
  chipText: { color: AppColors.text.secondary, fontWeight: "bold" },
  chipTextActive: { color: AppColors.primary },
  labelHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
    backgroundColor: "rgba(255, 171, 0, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 171, 0, 0.2)",
    borderRadius: 10,
    padding: 12,
    marginTop: -5,
  },
  labelHintText: {
    color: AppColors.accent.warning,
    fontSize: 12,
    flex: 1,
    lineHeight: 17,
  },
});
