import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppShadow, AppSpacing } from "@/constants/theme";

export const cards = StyleSheet.create({
  card: {
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xl,
    marginBottom: AppSpacing.xxl,
    borderWidth: 1,
    borderColor: AppColors.border.cyan,
    ...AppShadow.cyanSubtle,
  },
  cardElevated: {
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.xxxl,
    padding: AppSpacing.xxxl,
    borderWidth: 1,
    borderColor: AppColors.border.cyanMedium,
    ...AppShadow.cyanLarge,
  },
  cardActive: {
    borderColor: AppColors.border.cyanStrong,
    backgroundColor: "#1a2228",
    ...AppShadow.cyanSubtle,
  },
  cardRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    backgroundColor: AppColors.surface,
    padding: AppSpacing.lg,
    borderRadius: AppRadius.xxl,
    borderWidth: 1,
    borderColor: AppColors.border.subtle,
    marginBottom: AppSpacing.md,
  },
  cardHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: AppSpacing.sm,
    marginBottom: AppSpacing.lg,
    paddingBottom: AppSpacing.md,
    borderBottomWidth: 1,
    borderBottomColor: AppColors.border.subtle,
  },
  formCard: {
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xxl,
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: AppColors.border.cyan,
  },
  infoCard: {
    flexDirection: "row" as const,
    alignItems: "flex-start" as const,
    gap: AppSpacing.md,
    backgroundColor: "rgba(255, 171, 0, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 171, 0, 0.2)",
    borderRadius: AppRadius.lg,
    padding: AppSpacing.lg,
  },
  modalCard: {
    width: "100%",
    maxWidth: 350,
    backgroundColor: "#14171d",
    borderRadius: AppRadius.xxxl,
    padding: AppSpacing.xxxl,
    alignItems: "center" as const,
    borderWidth: 1,
    borderColor: AppColors.primary,
    ...AppShadow.cyanLarge,
  },
});
