import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppSpacing } from "@/constants/theme";

export const gestureDetailStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppColors.backgroundAlt },
  topBar: {
    paddingHorizontal: AppSpacing.xl,
    paddingTop: 12,
    paddingBottom: AppSpacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "#1b212a",
    justifyContent: "center",
    alignItems: "center",
  },
  title: { color: AppColors.text.primary, fontSize: AppSpacing.xl, fontWeight: "700" },
  content: { padding: AppSpacing.xl, paddingBottom: 32, gap: 12 },
  subtitle: { color: "#aeb8c7", marginBottom: 10 },
  loadingText: { color: "#aeb8c7" },
  emptyBox: {
    backgroundColor: "#151a22",
    borderWidth: 1,
    borderColor: "#2b3442",
    borderRadius: AppRadius.sm,
    padding: 14,
    alignItems: "center",
    gap: 6,
  },
  emptyText: { color: AppColors.text.secondary },
  card: {
    backgroundColor: "#1a1f28",
    borderWidth: 1,
    borderRadius: AppRadius.md,
    padding: 12,
    marginBottom: 12,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  letter: { color: AppColors.text.primary, fontSize: 22, fontWeight: "700" },
  levelBadge: {
    borderWidth: 1,
    borderRadius: 99,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "600",
  },
  category: { color: "#8f98a8", marginTop: 6, fontSize: 12 },
  desc: { color: "#c1c9d6", marginTop: AppSpacing.sm, marginBottom: 10 },
  stepsRow: { flexDirection: "row", gap: AppSpacing.sm },
  stepBox: { flex: 1 },
  stepTitle: { color: "#8f98a8", fontSize: 12, marginBottom: 6 },
  placeholder: {
    height: 78,
    backgroundColor: "#11161d",
    borderWidth: 1,
    borderColor: "#2b3442",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  footerNote: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#151a22",
    padding: 10,
    borderRadius: 10,
  },
  footerText: { color: AppColors.text.secondary, fontSize: 12 },
  previewImage: { width: "100%", height: "100%", resizeMode: "cover" },
  checkCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#00d084",
    alignItems: "center",
    justifyContent: "center",
  },
  learnBtn: {
    marginTop: AppSpacing.xl,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: AppSpacing.sm,
    paddingVertical: 10,
    borderRadius: 10,
  },
  unlearnedBtn: { backgroundColor: AppColors.primary },
  learnedBtn: {
    backgroundColor: "rgba(138, 146, 163, 0.1)",
    borderWidth: 1,
    borderColor: "#3a475c",
  },
  learnBtnText: { fontSize: 14, fontWeight: "700" },
  unlearnedBtnText: { color: "#081018" },
  learnedBtnText: { color: AppColors.text.secondary },
});
