import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppSpacing } from "@/constants/theme";

export const learnStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppColors.backgroundAlt },
  content: { padding: AppSpacing.xl, paddingBottom: 28 },
  header: { marginBottom: AppSpacing.xl, marginTop: AppSpacing.sm },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  title: { color: AppColors.text.primary, fontSize: 30, fontWeight: "700" },
  subtitle: { color: "#b8c0cc", marginTop: AppSpacing.sm, lineHeight: AppSpacing.xl },
  moduleSelectorContainer: { marginBottom: AppSpacing.xl },
  moduleScroll: { gap: 10, paddingRight: AppSpacing.xl },
  moduleBtn: {
    paddingHorizontal: AppSpacing.xl,
    paddingVertical: AppSpacing.sm,
    borderRadius: AppRadius.xxl,
    backgroundColor: AppColors.surface,
    borderWidth: 1,
    borderColor: "#2a3548",
  },
  moduleBtnActive: {
    backgroundColor: "rgba(0, 229, 255, 0.15)",
    borderColor: AppColors.primary,
  },
  moduleBtnText: { color: "#8a92a3", fontSize: 14, fontWeight: "700" },
  moduleBtnTextActive: { color: AppColors.primary },
  adminBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: AppColors.primary,
    paddingVertical: 12,
    paddingHorizontal: AppSpacing.xl,
    borderRadius: AppRadius.sm,
    marginBottom: AppSpacing.xl,
  },
  adminBtnText: { color: "#081018", fontWeight: "800", fontSize: 14 },
  levelSection: {
    backgroundColor: "#151a22",
    borderRadius: AppRadius.xl,
    padding: AppSpacing.xl,
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: "#232a35",
  },
  levelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: AppSpacing.sm,
  },
  levelTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
  },
  badge: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingVertical: 2,
    paddingHorizontal: AppSpacing.sm,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  badgeText: { color: "#8a92a3", fontSize: 10, fontWeight: "800" },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 4,
    marginTop: AppSpacing.sm,
  },
  progressText: { color: AppColors.text.primary, fontSize: 22, fontWeight: "900" },
  progressDetail: { color: "#8a92a3", fontSize: 12, fontWeight: "600", marginBottom: 2 },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  levelTitle: { color: AppColors.text.primary, fontSize: 18, fontWeight: "800" },
  levelSubtitle: { color: "#9cadc3", fontSize: 13, marginTop: 2 },
  barBg: {
    height: 6,
    borderRadius: 99,
    backgroundColor: "#2a2f3a",
    overflow: "hidden",
    marginBottom: AppSpacing.xl,
  },
  barFill: { height: 6, borderRadius: 99 },
  loadingText: {
    color: "#8a92a3",
    fontSize: 13,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 10,
  },
  emptyText: {
    color: "#8a92a3",
    fontSize: 13,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 10,
  },
  categoriesContainer: { gap: 10 },
  categoryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1a2230",
    padding: 14,
    borderRadius: AppRadius.sm,
    borderLeftWidth: 4,
  },
  categoryTitle: { color: "#eaf0fa", fontSize: 15, fontWeight: "700" },
  categoryCount: { color: "#8a92a3", fontSize: 12, marginTop: 2 },
  playBtn: {
    width: 32,
    height: 32,
    borderRadius: AppSpacing.xl,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  note: {
    marginTop: AppSpacing.sm,
    flexDirection: "row",
    gap: AppSpacing.sm,
    alignItems: "center",
    backgroundColor: "#151a22",
    padding: 12,
    borderRadius: AppRadius.sm,
  },
  noteText: {
    color: "#8a92a3",
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
  },
});
