import { StyleSheet } from "react-native";

export const camStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#10141a",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 50,
    paddingBottom: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  backBtn: { padding: 8, borderRadius: 12, backgroundColor: "#1c2026" },
  iconBtn: { padding: 8, borderRadius: 12, backgroundColor: "#1c2026" },
  iconBtnActive: {
    backgroundColor: "rgba(0, 229, 255, 0.15)",
    borderWidth: 1,
    borderColor: "#00e5ff",
  },
  modeBtnActive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    backgroundColor: "rgba(0, 229, 255, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.4)",
    maxWidth: 140,
  },
  modeBtnText: { fontSize: 11, fontWeight: "bold", color: "#00e5ff" },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: "bold", color: "#fff" },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#1c2026",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { fontSize: 11, fontWeight: "bold", textTransform: "uppercase" },
  cameraContainer: {
    marginHorizontal: 16,
    borderRadius: 24,
    backgroundColor: "#222",
    overflow: "hidden",
    position: "relative",
  },
  permissionBox: { flex: 1, alignItems: "center", justifyContent: "center", gap: 16 },
  warn: { color: "#888", textAlign: "center", fontSize: 14, paddingHorizontal: 20 },
  landmarkDot: { position: "absolute" },
  gestureOverlay: {
    position: "absolute",
    bottom: 24,
    alignSelf: "center",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    borderWidth: 1,
    borderColor: "#00e5ff",
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  gestureLabel: {
    fontSize: 40,
    fontWeight: "800",
    color: "#00e5ff",
    letterSpacing: 2,
  },
  confidencePill: {
    backgroundColor: "rgba(0, 229, 255, 0.15)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  confidenceText: { fontSize: 14, color: "#00e5ff", fontWeight: "bold" },
  edgeBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "rgba(0, 229, 255, 0.10)",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.3)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  edgeBadgeText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#00e5ff",
    textTransform: "uppercase",
  },
  errorBanner: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    backgroundColor: "rgba(255, 50, 50, 0.15)",
    borderWidth: 1,
    borderColor: "#ff6b6b",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: { color: "#ff6b6b", fontSize: 12, flex: 1, fontWeight: "500" },
  noHandBadge: {
    position: "absolute",
    bottom: 72,
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  noHandText: { color: "#888", fontSize: 12 },
  modelBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: "rgba(179, 136, 255, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(179, 136, 255, 0.35)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: 140,
  },
  modelBadgeText: { fontSize: 10, fontWeight: "bold", color: "#b388ff" },
  modelErrorBanner: {
    position: "absolute",
    top: 44,
    left: 12,
    right: 12,
    backgroundColor: "rgba(255, 50, 50, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 107, 107, 0.4)",
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  modelErrorTitle: { color: "#ff6b6b", fontSize: 13, fontWeight: "700" },
  modelErrorDesc: { color: "#aa6666", fontSize: 11, marginTop: 2 },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#14171d",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "#00e5ff",
    shadowColor: "#00e5ff",
    shadowOpacity: 0.3,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 10 },
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  modalTitle: { fontSize: 22, fontWeight: "800", color: "#fff" },
  modalSubtitle: {
    fontSize: 13,
    color: "#888",
    marginBottom: 20,
    lineHeight: 18,
  },
  modeOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1c2026",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "transparent",
    marginBottom: 10,
  },
  modeOptionActive: {
    backgroundColor: "rgba(0, 229, 255, 0.12)",
    borderColor: "#00e5ff",
    shadowColor: "#00e5ff",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  modeOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  modeLabel: { fontSize: 15, fontWeight: "700", color: "#aaa" },
  modeLabelActive: { color: "#00e5ff" },
  modeDesc: { fontSize: 11, color: "#666", marginTop: 2 },
  activeDotOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(0, 229, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  activeDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#00e5ff",
  },
  modalCloseBtn: {
    marginTop: 10,
    alignItems: "center",
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#1c2026",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  modalCloseBtnText: { color: "#888", fontSize: 15, fontWeight: "600" },
});
