import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppShadow, AppSpacing } from "@/constants/theme";

export const editProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.backgroundAlt,
    paddingHorizontal: AppSpacing.xl,
    paddingTop: 50,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 30,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: AppRadius.sm,
    backgroundColor: AppColors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: { fontSize: 20, fontWeight: "800", color: AppColors.text.primary },
  avatarSection: { alignItems: "center", marginBottom: 30 },
  avatarContainer: { position: "relative", marginBottom: 16 },
  avatarImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: AppColors.primary,
  },
  avatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: AppColors.surface,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: AppColors.border.cyan,
    borderStyle: "dashed",
  },
  editBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: AppColors.primary,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: AppColors.backgroundAlt,
    ...AppShadow.cyan,
    elevation: 5,
  },
  uploadBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
    backgroundColor: AppColors.primary,
    paddingVertical: 12,
    paddingHorizontal: AppSpacing.xxl,
    borderRadius: AppRadius.sm,
    ...AppShadow.cyan,
    elevation: 5,
  },
  uploadBtnText: { color: "#000", fontWeight: "bold", fontSize: 14 },
  formCard: {
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xxl,
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: AppColors.border.cyan,
  },
  fieldLabel: {
    color: AppColors.text.secondary,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 12,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: AppColors.background,
    borderRadius: AppRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: AppSpacing.xl,
    marginBottom: AppSpacing.xl,
  },
  input: {
    flex: 1,
    color: AppColors.primary,
    fontSize: 16,
    paddingVertical: 16,
    fontWeight: "600",
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: AppSpacing.sm,
    backgroundColor: AppColors.primary,
    paddingVertical: 16,
    borderRadius: AppRadius.sm,
    ...AppShadow.cyan,
    elevation: 5,
  },
  saveBtnText: { color: "#000", fontWeight: "bold", fontSize: 16 },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "rgba(255, 171, 0, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 171, 0, 0.2)",
    borderRadius: AppRadius.md,
    padding: AppSpacing.xl,
  },
  infoText: {
    fontSize: 13,
    color: AppColors.text.muted,
    flex: 1,
    lineHeight: 19,
  },
});
