import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppSpacing } from "@/constants/theme";

export function makeGestureDetailStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundAlt },
  topBar: {
    paddingHorizontal: AppSpacing.xl,
    paddingTop: 12,
    paddingBottom: AppSpacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  title: { color: colors.text.primary, fontSize: AppSpacing.xl, fontWeight: "700" },
  content: { padding: AppSpacing.xl, paddingBottom: 32, gap: 12 },
  subtitle: { color: colors.text.tertiary, marginBottom: 10 },
  loadingText: { color: colors.text.tertiary },
  emptyBox: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: AppRadius.sm,
    padding: 14,
    alignItems: "center",
    gap: 6,
  },
  emptyText: { color: colors.text.secondary },
  card: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: AppRadius.md,
    padding: 12,
    marginBottom: 12,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  letter: { color: colors.text.primary, fontSize: 22, fontWeight: "700" },
  levelBadge: {
    borderWidth: 1,
    borderRadius: 99,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "600",
  },
  category: { color: colors.text.muted, marginTop: 6, fontSize: 12 },
  desc: { color: colors.text.alt, marginTop: AppSpacing.sm, marginBottom: 10 },
  stepsRow: { flexDirection: "row", gap: AppSpacing.sm },
  stepBox: { flex: 1 },
  stepTitle: { color: colors.text.muted, fontSize: 12, marginBottom: 6 },
  placeholder: {
    height: 78,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  footerNote: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.surface,
    padding: 10,
    borderRadius: 10,
  },
  footerText: { color: colors.text.secondary, fontSize: 12 },
  previewImage: { width: "100%", height: "100%", resizeMode: "cover" },
  checkCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.accent.green,
    alignItems: "center",
    justifyContent: "center",
  },
  learnBtn: {
    marginTop: AppSpacing.xl,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: AppSpacing.sm,
    paddingVertical: 10,
    borderRadius: 10,
  },
  unlearnedBtn: { backgroundColor: colors.primary },
  learnedBtn: {
    backgroundColor: "rgba(138, 146, 163, 0.1)",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  learnBtnText: { fontSize: 14, fontWeight: "700" },
  unlearnedBtnText: { color: colors.background },
  learnedBtnText: { color: colors.text.secondary },
});
}

export const gestureDetailStyles = makeGestureDetailStyles;
