import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppShadow, AppSpacing } from "@/constants/theme";

export function makeHomeStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundAlt },
  iconCircle: {
    width: 40,
    height: 30,
    borderRadius: 35,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  avatarImage: {
    width: 50,
    height: 50,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: colors.primary,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: AppSpacing.xl,
    alignItems: "center",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
  },
  logoText: { color: colors.text.alt, fontSize: AppSpacing.xl, fontWeight: "bold" },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.xl,
  },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  content: { padding: AppSpacing.xl, paddingBottom: 10 },
  hero: { marginBottom: AppSpacing.xxl },
  title: { fontSize: 40, fontWeight: "bold", color: colors.text.primary },
  subtitle: { color: colors.text.tertiary, marginVertical: 12 },
  mainButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    padding: 12,
    borderRadius: AppRadius.sm,
    gap: AppSpacing.sm,
    ...AppShadow.cyanLarge,
    elevation: 8,
  },
  buttonText: { fontWeight: "bold", color: "#00363d" },
  grid: { gap: AppSpacing.xl },
  cardLarge: {
    backgroundColor: colors.surface,
    padding: AppSpacing.xl,
    borderRadius: AppRadius.xl,
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.1)",
    shadowColor: "#000",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  card: {
    backgroundColor: colors.surfaceAlt,
    padding: AppSpacing.xl,
    borderRadius: AppRadius.xl,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  cardWide: {
    backgroundColor: colors.surface,
    padding: AppSpacing.xl,
    borderRadius: AppRadius.xl,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.subtle,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  cardTitle: { color: colors.text.primary, fontWeight: "bold", marginTop: AppSpacing.sm },
  cardText: { color: colors.text.muted, marginTop: 4 },
  cardTextSmall: { color: colors.text.muted, fontSize: 12 },
  pipeline: { marginTop: 32 },
  pipelineTitle: { color: colors.text.secondary, marginBottom: 12 },
  tags: { flexDirection: "row", gap: AppSpacing.sm },
  tag: { backgroundColor: colors.background, padding: AppSpacing.sm, borderRadius: 20 },
  tagText: { color: colors.primary, fontSize: 12 },
  rankingContainer: {
    backgroundColor: colors.surface,
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xl,
    marginTop: AppSpacing.sm,
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.1)",
  },
  rankingHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: AppSpacing.xl,
  },
  rankingTitle: {
    color: colors.text.primary,
    fontSize: 18,
    fontWeight: "bold",
  },
  seeAllText: { color: colors.primary, fontSize: 12, fontWeight: "600" },
  rankRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 10,
    borderRadius: AppRadius.sm,
  },
  rankLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  rankNum: {
    color: colors.text.tertiary,
    fontWeight: "bold",
    width: 20,
  },
  avatarMini: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  rankName: {
    color: colors.text.alt,
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
  },
  rankPoints: { color: colors.primary, fontSize: 13, fontWeight: "bold" },
  othersList: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
    paddingTop: AppSpacing.xl,
  },
});
}

export const homeStyles = makeHomeStyles;
