import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppSpacing } from "@/constants/theme";

export function makeLearnStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundAlt },
  content: { padding: AppSpacing.xl, paddingBottom: 28 },
  header: { marginBottom: AppSpacing.xl, marginTop: AppSpacing.sm },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  title: { color: colors.text.primary, fontSize: 30, fontWeight: "700" },
  subtitle: { color: colors.text.tertiary, marginTop: AppSpacing.sm, lineHeight: AppSpacing.xl },
  moduleSelectorContainer: { marginBottom: AppSpacing.xl },
  moduleScroll: { gap: 10, paddingRight: AppSpacing.xl },
  moduleBtn: {
    paddingHorizontal: AppSpacing.xl,
    paddingVertical: AppSpacing.sm,
    borderRadius: AppRadius.xxl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  moduleBtnActive: {
    backgroundColor: colors.border.cyanMedium,
    borderColor: colors.primary,
  },
  moduleBtnText: { color: colors.text.secondary, fontSize: 14, fontWeight: "700" },
  moduleBtnTextActive: { color: colors.primary },
  adminBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: AppSpacing.xl,
    borderRadius: AppRadius.sm,
    marginBottom: AppSpacing.xl,
  },
  adminBtnText: { color: "#081018", fontWeight: "800", fontSize: 14 },
  levelSection: {
    backgroundColor: colors.surface,
    borderRadius: AppRadius.xl,
    padding: AppSpacing.xl,
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  levelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: AppSpacing.sm,
  },
  levelTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
  },
  badge: {
    backgroundColor: colors.border.subtle,
    paddingVertical: 2,
    paddingHorizontal: AppSpacing.sm,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  badgeText: { color: colors.text.secondary, fontSize: 10, fontWeight: "800" },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 4,
    marginTop: AppSpacing.sm,
  },
  progressText: { color: colors.text.primary, fontSize: 22, fontWeight: "900" },
  progressDetail: { color: colors.text.secondary, fontSize: 12, fontWeight: "600", marginBottom: 2 },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  levelTitle: { color: colors.text.primary, fontSize: 18, fontWeight: "800" },
  levelSubtitle: { color: colors.text.muted, fontSize: 13, marginTop: 2 },
  barBg: {
    height: 6,
    borderRadius: 99,
    backgroundColor: colors.surfaceAlt,
    overflow: "hidden",
    marginBottom: AppSpacing.xl,
  },
  barFill: { height: 6, borderRadius: 99 },
  loadingText: {
    color: colors.text.secondary,
    fontSize: 13,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 10,
  },
  emptyText: {
    color: colors.text.secondary,
    fontSize: 13,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 10,
  },
  categoriesContainer: { gap: 10 },
  categoryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceAlt,
    padding: 14,
    borderRadius: AppRadius.sm,
    borderLeftWidth: 4,
  },
  categoryTitle: { color: colors.text.primary, fontSize: 15, fontWeight: "700" },
  categoryCount: { color: colors.text.secondary, fontSize: 12, marginTop: 2 },
  playBtn: {
    width: 32,
    height: 32,
    borderRadius: AppSpacing.xl,
    backgroundColor: colors.border.subtle,
    alignItems: "center",
    justifyContent: "center",
  },
  note: {
    marginTop: AppSpacing.sm,
    flexDirection: "row",
    gap: AppSpacing.sm,
    alignItems: "center",
    backgroundColor: colors.surface,
    padding: 12,
    borderRadius: AppRadius.sm,
  },
  noteText: {
    color: colors.text.secondary,
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
  },
});
}

export const learnStyles = makeLearnStyles;
