import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppShadow, AppSpacing } from "@/constants/theme";

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.backgroundAlt,
    justifyContent: "center",
    alignItems: "center",
    padding: AppSpacing.xl,
  },
  card: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.xxxl,
    padding: AppSpacing.xxxl,
    borderWidth: 1,
    borderColor: AppColors.border.cyanMedium,
    ...AppShadow.cyanLarge,
  },
  iconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: AppColors.primary,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: AppColors.text.primary,
    textAlign: "center",
    marginBottom: AppSpacing.md,
  },
  subtitle: {
    fontSize: 13,
    color: AppColors.text.secondary,
    textAlign: "center",
    marginBottom: AppSpacing.xxxl,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: AppColors.backgroundAlt,
    borderRadius: AppRadius.md,
    borderWidth: 1,
    borderColor: AppColors.border.subtle,
    marginBottom: 15,
    overflow: "hidden",
  },
  icon: { padding: 15 },
  input: {
    flex: 1,
    color: AppColors.primary,
    fontSize: 16,
    paddingVertical: 15,
    fontWeight: "600",
  },
  mainBtn: {
    backgroundColor: AppColors.primary,
    borderRadius: AppRadius.md,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: AppSpacing.md,
    ...AppShadow.cyan,
  },
  mainBtnText: { color: "#000", fontSize: 16, fontWeight: "bold" },
  toggleBtn: { marginTop: 25, alignSelf: "center", padding: AppSpacing.md },
  toggleText: {
    color: AppColors.text.secondary,
    fontSize: 14,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
});
