import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppSpacing } from "@/constants/theme";

export function makeManageLearningStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundAlt },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: AppSpacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.surface,
    backgroundColor: "#151a22",
  },
  backBtn: {
    padding: AppSpacing.sm,
    marginRight: AppSpacing.sm,
    borderRadius: AppSpacing.sm,
    backgroundColor: colors.surface,
  },
  titleContainer: { flex: 1 },
  title: { color: colors.text.primary, fontSize: AppSpacing.xl, fontWeight: "700" },
  subtitle: { color: colors.text.secondary, fontSize: 12, marginTop: 2 },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: AppSpacing.sm,
    borderRadius: AppSpacing.sm,
    backgroundColor: colors.primary,
  },
  addBtnText: { color: "#081018", fontWeight: "700", fontSize: 13 },
  content: { padding: AppSpacing.xl, paddingBottom: 40, gap: 12 },
  emptyText: {
    color: colors.text.secondary,
    textAlign: "center",
    marginTop: 40,
    fontSize: 15,
  },
  card: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: AppRadius.sm,
    padding: AppSpacing.xl,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#283345",
  },
  cardLeft: { flex: 1 },
  cardTitle: { color: colors.text.primary, fontSize: 16, fontWeight: "700" },
  cardSubtitle: { color: "#9cadc3", fontSize: 13, marginTop: 4 },
  cardActions: { flexDirection: "row", gap: AppSpacing.sm },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: AppSpacing.sm,
    backgroundColor: "#2a3548",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBtn: { backgroundColor: "rgba(255, 134, 134, 0.1)" },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(5,8,12,0.8)",
    justifyContent: "center",
    padding: AppSpacing.xl,
  },
  modalCard: {
    backgroundColor: "#121821",
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xxl,
    borderWidth: 1,
    borderColor: "#283345",
    maxHeight: "85%",
  },
  modalTitle: {
    color: colors.text.primary,
    fontSize: 22,
    fontWeight: "800",
    marginBottom: AppSpacing.xl,
  },
  inputLabel: {
    color: "#9cadc3",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#1a2230",
    borderWidth: 1,
    borderColor: "#2a3548",
    borderRadius: AppRadius.sm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text.primary,
    fontSize: 15,
  },
  levelPicker: {
    marginTop: 2,
    backgroundColor: "#1a2230",
    borderWidth: 1,
    borderColor: "#2a3548",
    borderRadius: AppRadius.sm,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  levelPickerText: { color: "#eaf0fa", fontWeight: "700", fontSize: 15 },
  modalActions: {
    marginTop: AppSpacing.xxl,
    flexDirection: "row",
    gap: 12,
  },
  modalBtn: {
    flex: 1,
    borderRadius: AppRadius.sm,
    paddingVertical: 14,
    alignItems: "center",
  },
  cancelBtn: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#3a475c",
  },
  saveBtn: { backgroundColor: colors.primary },
  cancelText: { color: "#d4ddeb", fontWeight: "700", fontSize: 15 },
  saveText: { color: "#081018", fontWeight: "800", fontSize: 15 },
  imagesRow: { flexDirection: "row", gap: AppSpacing.sm, marginTop: 4 },
  imageBox: {
    flex: 1,
    height: 80,
    backgroundColor: "#1a2230",
    borderWidth: 1,
    borderColor: "#2a3548",
    borderRadius: AppRadius.sm,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  previewImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
    opacity: 0.8,
  },
  imageBoxText: {
    color: "#eaf0fa",
    fontSize: 11,
    marginTop: 4,
    fontWeight: "bold",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 4,
    borderRadius: 4,
  },
});
}

export const manageLearningStyles = makeManageLearningStyles;
