import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppShadow, AppSpacing } from "@/constants/theme";

export const modelsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.backgroundAlt,
    padding: AppSpacing.xl,
    paddingTop: 50,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    marginBottom: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: AppRadius.sm,
    backgroundColor: AppColors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  title: { fontSize: 24, fontWeight: "800", color: AppColors.text.primary },
  subtitle: {
    fontSize: 13,
    color: AppColors.text.secondary,
    marginBottom: AppSpacing.xxl,
    lineHeight: 19,
  },
  list: { gap: 16 },
  emptyBox: { alignItems: "center", marginTop: 60, gap: 10 },
  emptyText: { color: AppColors.text.secondary, fontSize: 16, fontWeight: "600" },
  emptyHint: {
    color: AppColors.text.tertiary,
    fontSize: 13,
    textAlign: "center",
    paddingHorizontal: 40,
  },
  card: {
    backgroundColor: AppColors.surface,
    padding: AppSpacing.xl,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  cardActive: {
    borderColor: AppColors.border.cyan,
    backgroundColor: "#1a2228",
    ...AppShadow.cyanSubtle,
    elevation: 6,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  modelName: { color: AppColors.text.primary, fontWeight: "700", fontSize: 18 },
  modelNameActive: { color: AppColors.primary },
  typeBadge: {
    backgroundColor: AppColors.background,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: AppSpacing.sm,
    borderWidth: 1,
    borderColor: "#333",
  },
  modelType: {
    color: AppColors.text.secondary,
    fontSize: 10,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  submodelsArea: {
    backgroundColor: AppColors.background,
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    gap: AppSpacing.sm,
  },
  submodelRow: { flexDirection: "row", alignItems: "center", gap: AppSpacing.sm },
  submodelText: { color: AppColors.text.muted, fontSize: 12 },
  metricsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    backgroundColor: AppColors.background,
    borderRadius: AppRadius.sm,
    padding: 14,
  },
  metricBox: { flex: 1, alignItems: "center" },
  metricValue: { color: AppColors.primary, fontSize: 22, fontWeight: "800" },
  metricLabel: {
    color: AppColors.text.tertiary,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    marginTop: 4,
  },
  metricDivider: {
    width: 1,
    height: 30,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  activeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
    backgroundColor: "rgba(76, 175, 80, 0.08)",
    borderRadius: AppSpacing.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
  },
  activeBadgeText: { color: "#4caf50", fontSize: 12, fontWeight: "600" },
  activateBtn: {
    backgroundColor: AppColors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
    borderRadius: AppRadius.sm,
    gap: 10,
    ...AppShadow.cyan,
    elevation: 4,
  },
  activateBtnActive: {
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    borderWidth: 1,
    borderColor: AppColors.border.cyan,
    shadowOpacity: 0,
    elevation: 0,
  },
  activateBtnText: { color: "#000", fontWeight: "bold", fontSize: 14 },
  activateBtnTextActive: { color: AppColors.primary },
});
