import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppSpacing } from "@/constants/theme";

export function makeProfileStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundAlt },
  scrollContent: {
    padding: AppSpacing.xl,
    paddingTop: 60,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { fontSize: 28, fontWeight: "800", color: colors.text.primary },
  langBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    paddingVertical: AppSpacing.sm,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border.cyan,
  },
  langText: { color: colors.primary, fontWeight: "700", fontSize: 14 },
  profileCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    padding: 30,
    borderRadius: AppRadius.xxl,
    marginBottom: AppSpacing.xl,
    borderWidth: 1,
    borderColor: colors.border.cyan,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    position: "relative",
  },
  avatarImage: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  adminBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: colors.podium.gold,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  editAvatarBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: "rgba(0, 229, 255, 0.8)",
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  nameText: {
    fontSize: 22,
    color: colors.text.primary,
    fontWeight: "700",
    marginBottom: 5,
  },
  roleText: {
    fontSize: 14,
    color: colors.text.secondary,
    fontWeight: "600",
    marginBottom: 16,
  },
  adminLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    padding: 12,
    borderRadius: AppRadius.sm,
    gap: 10,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "rgba(255, 107, 107, 0.2)",
    width: "100%",
  },
  adminLinkText: { color: colors.accent.danger, fontWeight: "bold", fontSize: 14 },
  editProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    paddingVertical: 10,
    paddingHorizontal: AppSpacing.xl,
    borderRadius: AppRadius.sm,
    borderWidth: 1,
    borderColor: colors.border.cyan,
  },
  editProfileBtnText: { color: colors.primary, fontWeight: "700", fontSize: 13 },
  statsCard: {
    backgroundColor: colors.surface,
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xl,
    marginBottom: AppSpacing.xl,
  },
  statsTitle: {
    color: colors.text.primary,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: AppSpacing.xl,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: AppSpacing.xl,
  },
  statBox: { flex: 1, alignItems: "center" },
  statValueText: {
    color: colors.primary,
    fontSize: 32,
    fontWeight: "800",
    marginBottom: 5,
  },
  statLabelText: {
    color: colors.text.secondary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  divider: {
    width: 1,
    height: 40,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  rankingBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    padding: 15,
    borderRadius: AppRadius.sm,
    gap: 5,
    marginBottom: 12,
  },
  rankingBtnText: { color: colors.primary, fontWeight: "bold" },
  aboutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    padding: 15,
    borderRadius: AppRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  aboutBtnText: { color: colors.text.secondary, fontWeight: "600", fontSize: 14 },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 15,
    backgroundColor: "rgba(255, 68, 68, 0.1)",
    gap: 10,
    marginTop: AppSpacing.xl,
  },
  logoutText: { color: "#ff4444", fontWeight: "bold", fontSize: 16 },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  langModal: {
    width: "80%",
    maxWidth: 300,
    backgroundColor: colors.surface,
    borderRadius: AppRadius.xxl,
    padding: AppSpacing.xl,
    borderWidth: 1,
    borderColor: colors.border.cyanStrong,
  },
  modalTitleText: {
    color: colors.text.primary,
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: AppSpacing.xl,
    textAlign: "center",
  },
  langItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: AppRadius.sm,
    marginBottom: AppSpacing.sm,
    gap: 12,
  },
  langItemActive: { backgroundColor: "rgba(0, 229, 255, 0.1)" },
  langFlag: { fontSize: AppSpacing.xl },
  langFlagActive: { fontSize: AppSpacing.xl },
  langNameText: {
    flex: 1,
    color: colors.text.secondary,
    fontSize: 16,
    fontWeight: "600",
  },
  langNameActive: { color: colors.text.primary },
});
}

export const profileStyles = makeProfileStyles;
