import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppSpacing } from "@/constants/theme";

export function makeRankingStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: AppSpacing.xl,
    paddingTop: 50,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  title: { fontSize: 22, fontWeight: "800", color: colors.text.primary },
  subtitle: {
    fontSize: 13,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: 30,
    paddingHorizontal: AppSpacing.xl,
  },
  podiumContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    height: 220,
    marginBottom: 30,
    gap: 10,
  },
  podiumCol: { alignItems: "center", width: "30%" },
  podiumName: {
    color: colors.text.primary,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 4,
    textAlign: "center",
  },
  podiumSamples: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 10,
  },
  podiumBox: {
    width: "100%",
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 15,
    shadowColor: "#ffdf00",
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  podiumRank: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.text.primary,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  podiumEmpty: { width: "30%" },
  listContent: { paddingBottom: 40 },
  rankRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: AppRadius.xl,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  rankLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  rankNum: {
    color: colors.text.tertiary,
    fontSize: 16,
    fontWeight: "800",
    width: 20,
  },
  avatarMini: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.cyan,
  },
  rankRowName: {
    color: colors.text.primary,
    fontSize: 15,
    fontWeight: "600",
  },
  pointsBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border.cyan,
  },
  rankRowPoints: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: "700",
  },
});
}

export const rankingStyles = makeRankingStyles;
