import { StyleSheet } from "react-native";
import { AppColors, AppRadius, AppShadow, AppSpacing } from "@/constants/theme";

export const trainStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.backgroundAlt,
    padding: AppSpacing.xl,
    paddingTop: 50,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    marginBottom: AppSpacing.xl,
  },
  title: { fontSize: 24, fontWeight: "bold", color: AppColors.text.primary },
  form: { gap: 15 },
  tabsRow: {
    flexDirection: "row",
    backgroundColor: AppColors.surface,
    borderRadius: 10,
    padding: 4,
    marginBottom: 10,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: AppSpacing.sm,
  },
  tabActive: { backgroundColor: "rgba(0, 229, 255, 0.15)" },
  tabText: { color: AppColors.text.secondary, fontWeight: "bold", fontSize: 13 },
  tabTextActive: { color: AppColors.primary },
  label: {
    color: AppColors.text.secondary,
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 10,
  },
  input: {
    backgroundColor: AppColors.surface,
    color: AppColors.primary,
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AppColors.border.cyan,
    fontSize: 18,
    fontWeight: "bold",
  },
  modelsScroll: { flexGrow: 0, marginBottom: 5 },
  chip: {
    backgroundColor: AppColors.surface,
    paddingHorizontal: AppSpacing.xl,
    paddingVertical: 12,
    borderRadius: 10,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  chipActive: {
    borderColor: AppColors.primary,
    backgroundColor: "rgba(0, 229, 255, 0.1)",
  },
  chipText: { color: AppColors.text.secondary, fontWeight: "bold" },
  chipTextActive: { color: AppColors.primary },
  dsButton: {
    padding: AppSpacing.xl,
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  dsButtonActive: {
    borderColor: AppColors.primary,
    backgroundColor: "rgba(0, 229, 255, 0.05)",
  },
  captureBtn: {
    backgroundColor: AppColors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: AppSpacing.xl,
    borderRadius: AppRadius.sm,
    gap: 10,
    marginTop: AppSpacing.xl,
    ...AppShadow.cyan,
  },
  captureBtnText: { color: "#000", fontWeight: "bold", fontSize: 16 },
  statusBox: {
    marginTop: AppSpacing.xl,
    padding: AppSpacing.xl,
    backgroundColor: AppColors.surface,
    borderRadius: AppRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
});
