import { StyleSheet } from "react-native";
import { AppColorTokens, AppRadius, AppSpacing } from "@/constants/theme";

export function makeTranscriptionStyles(colors: AppColorTokens) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.backgroundAlt },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: AppSpacing.xl,
    paddingTop: 12,
    paddingBottom: 12,
  },
  title: { color: colors.text.primary, fontSize: 22, fontWeight: "800" },
  inputArea: { paddingHorizontal: AppSpacing.xl },
  inputContainer: {
    backgroundColor: colors.surface,
    borderRadius: AppRadius.xl,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    overflow: "hidden",
  },
  input: {
    color: colors.text.primary,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: AppSpacing.sm,
    minHeight: 60,
    maxHeight: 100,
    textAlignVertical: "top",
  },
  inputFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  charCount: { color: colors.text.secondary, fontSize: 12 },
  translateBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: AppSpacing.xl,
    paddingVertical: AppSpacing.sm,
    borderRadius: 10,
  },
  translateBtnDisabled: { backgroundColor: colors.surfaceAlt, opacity: 0.5 },
  translateBtnText: { color: "#081018", fontWeight: "700", fontSize: 14 },
  webviewContainer: {
    flex: 1,
    margin: AppSpacing.xl,
    marginTop: 12,
    borderRadius: AppRadius.xl,
    overflow: "hidden",
    backgroundColor: colors.backgroundAlt,
  },
  webview: { flex: 1, backgroundColor: colors.backgroundAlt },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    backgroundColor: colors.backgroundAlt,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: { color: colors.text.secondary, fontSize: 14 },
  subtitleBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: AppSpacing.sm,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  subtitleText: { color: colors.text.alt, fontSize: 13, flex: 1 },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: AppSpacing.sm,
    paddingHorizontal: AppSpacing.xl,
  },
  footerText: { color: colors.text.secondary, fontSize: 11 },
});
}

export const transcriptionStyles = makeTranscriptionStyles;
